# Site
title: 'Conducción Neumática'
description: 'Creada y dirigida por Genietta Varsi, La Conducción Neumática es un proyecto multi-medios y colectivo de acciones aéreas que investiga los fenómenos del aire fuera y dentro del cuerpo, con el objetivo de pensarlos, des-pensarlos, hacerlos, des-hacerlos y mezclarlos.'
keywords: 'art, arte, respiración, aire, air, breathing, conducción, neumática, Genietta, Varsi, Genietta Varsi'
artist: 'Genietta Varsi'

# URL
url: 'https://conduccionneumatica.org'
baseurl: ''
include: ['_pages']

# Build settings
markdown: kramdown
port: 6886
future: false
